name: XmlLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  XML-Lint:
    name: XML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: XML Lint
        uses: anyone-developer/anyone-validate-xml@0.9.2
        with:
          file-extension: '.xml'
          ignore-files: 'README.md'
          ignore-directories: '.git'
          read-path: './'
